name: 'Upload to Modio'
description: 'GitHub Action for uploading mods to mod.io'
author: 'nickelc'
branding:
  color: 'yellow'
  icon: 'package'

inputs:
  token:
    description: "The user's access token"
    required: true
  test-env:
    description: 'Use test environment'
    required: false

  game:
    description: 'Unique id of the game'
    required: true
  mod:
    description: 'Unique id of the mod'
    required: true
  path:
    description: 'The path to the mod file you want to upload'
    required: true

  version:
    description: 'Version of the mod file'
    required: false
  changelog:
    description: 'Changelog of the mod file'
    required: false
  changelog-path:
    description: 'Path to changelog of the mod file'
    required: false
  active:
    description: 'Label this upload as the current release'
    required: false
  filehash:
    description: 'Filehash of the mod file'
    required: false
  metadata:
    description: 'Metadata blob of the mod file'
    required: false
  metadata-path:
    description: 'Path to the metadata blob of the mod file'
    required: false

outputs:
  id:
    description: 'Unique id of the uploaded file'
    value: ${{ steps.upload.outputs.id }}
  url:
    description: 'Download URL for the file'
    value: ${{ steps.upload.outputs.url }}
  fileshash:
    description: 'MD5 of the uploaded file'
    value: ${{ steps.upload.outputs.filehash }}
  response:
    description: 'File to response content of the request'
    value: ${{ steps.upload.outputs.response }}

runs:
  using: composite
  steps:
    - id: upload
      shell: bash
      run: ${GITHUB_ACTION_PATH}/upload.sh
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TEST_URL: ${{ inputs.test-env }}
        INPUT_GAME: ${{ inputs.game }}
        INPUT_MOD: ${{ inputs.mod }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_CHANGELOG: ${{ inputs.changelog-path || inputs.changelog }}
        INPUT_ACTIVE: ${{ inputs.active }}
        INPUT_FILEHASH: ${{ inputs.filehash }}
        INPUT_METADATA: ${{ inputs.metadata-path || inputs.metadata }}
