name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: upload
        env:
          MODIO_DEBUG_OVERRIDE_URL: https://httpbin.org/post
        with:
          token: foobar
          game: 123
          mod: 456
          path: action.yml

          version: "1.0"
          changelog-path: README.md
          metadata: '{"foo":"bar"}'

      - run: |
          : echo output
          echo "${{ steps.upload.outputs.response }}"
          cat "${{ steps.upload.outputs.response }}"
        shell: bash
